### ISSUE TITLE
Gozim on on raspberry pi modèle B+ 

### ISSUE THREAD

**Issue by mikamboo** [akhenakh/gozim#19]
Hello @akhenakh ,

Thanks for this great project that i recently discovered !

I try to run Gozim on my Raspberry Pi (fresh install of Raspbian 7 wheezy) but I get this error : 

```
gozimhttpd: error while loading shared libraries: libleveldb.so.1: cannot open shared object file: No such file or directory
```
So, I'm trying to find a way to install __libleveldb__ on my RPI, any suggestion ?

**Comment by mikamboo** [comment]
Found !!!

I follwed this really simple tutorial : http://techoverflow.net/blog/2012/12/14/compiling-installing-leveldb-on-linux/

That worked perfectly !

**Comment by akhenakh** [comment]
Happy you found it

**Comment by xthursdayx** [comment]
@mikamboo I'm having the exact same problem as you, but unfortunately I didn't really understand that tutorial you linked. Could you tell me what you did to install libleveldb? Thanks in advance.

**Comment by mikamboo** [comment]
Hi @xthursdayx !

This issue is so old, i don't remeber all, but if you see the tutorial link, there is [this link](https://techoverflow.net/2012/12/14/compiling-installing-leveldb-on-linux/)  that explains Compiling & Installing LevelDB on Linux.

**Comment by xthursdayx** [comment]
Yeah, thanks. I looked at that link but found it confusing. Thanks for following up anyway though!
