### ISSUE TITLE
Index File Size: gozim vs kiwix

### ISSUE THREAD

**Issue by manishasia** [akhenakh/gozim#25]
The non-indexed ZIM version for English Wikipedia (dated 02/2016) as provided by kind Kiwix guys weighs 51.8GB. 
Kiwix’s index of this ZIM results in 20.2GB

Kiwix’s ZIM + Index is adding to 72GB, which I am unable to squeeze into a 64GB USB stick. 

My question is if we know (or can estimate) the size of index for the above ZIM if GOZIM is used ? Can it be reduced further ? 

Thanks
Manish
www.OfflineAccess.com

**Comment by akhenakh** [comment]
There is no way to estimate the size of the index, gozim relies on Bleve for indexing, here is the sizes running the gozim demo:

1.3G	wikipedia_en_all_07_2014_stem.idx
41G	wikipedia_en_all_07_2014.zim
