### ISSUE TITLE
Different Default Sorting Method

### ISSUE THREAD

**Issue by doobeh** [akhenakh/gozim#27]
Hi, I was looking into Gozim to deploy Wikipedia to school-kids in offline locations in Malawi (A Pi3 serving a collection of cheap tablets with data).  The initial usage of Gozim inevitably means clicking 'Browse' and so your very first experience is unfortunately welcomed with entries such as "!!!Fuck You!!!" etc.

I know you don't control the entries of Wikipedia-- would it be possible however to just do a A-Z sort then Numbers -> Characters?  It might make the 'Browse' option more welcoming.

**Comment by akhenakh** [comment]
Unfortunately the browse handler goes to page 0 which translates to element 0 in the zim file.

We could do something that lookup for >A and seek to this page but that won't work for all zim (some may not contain anything starting by letter A or not in alphabetical order ...)
We could pass a default start page number to the server ...

**Comment by doobeh** [comment]
Thanks, I guess I'm in an exclusively Wikipedia serving frame of mind.  I'm just going to fork off a copy and edit the templates to hide the browse feature, and just do a small custom welcome screen instead.  Thanks for the feedback— this project is going to really help some remote people!
