### ISSUE TITLE
Changing default port

### ISSUE THREAD

**Issue by xthursdayx** [akhenakh/gozim#40]
Is there a way to change the default port to something else other than 8080?

**Comment by Aws505** [comment]
It appears to just be a run flag for gozimhttpd 
Unsurprisingly, it's the "-port=" flag.

Set -port=8888 (or whatever port you want) and Bob's your uncle

**Comment by xthursdayx** [comment]
> It appears to just be a run flag for gozimhttpd 
> 
> Unsurprisingly, it's the "-port=" flag.
> 
> 
> 
> Set -port=8888 (or whatever port you want) and Bob's your uncle

Awesome, thanks for following up!
